image: ddavison/soapui

before_script:
  - curl -sL https://deb.nodesource.com/setup_4.x | bash -
  - apt-get install -y nodejs
  - apt-get install -y build-essential
  - npm install
  - PORT=4000 node . &

test:
  script:
    - npm test
    - /opt/SoapUI/bin/testrunner.sh -PPORT=4000 ./Q3-Training-Tests-soapui-project.xml

